### ISSUE TITLE
Disable registration

### ISSUE THREAD

**Issue by jostyee** [angristan/feedbin-docker#3]
Hi,

Thanks for this repo, I can finally set up a feedbin instance on my own device. As it's only for personal using, I wonder if there's a setting that I can disable user signups?

**Comment by angristan** [comment]
Hello, sadly no, I made an issue here: https://github.com/feedbin/feedbin/issues/406

**Comment by jariz** [comment]
Hi there to anyone reading this!
I made a quick workaround for this by adding the following to the top of my Caddyfile:
```diff
feedbin.domain.tld {
  gzip
  proxy / http://feedbin-web:3000 {
    transparent
  }
+  status 403 /signup
+  status 403 /users
}
```

@angristan maybe an idea to add this to the README as the upstream issue isn't getting that much traction?

**Comment by angristan** [comment]
Great idea @jariz, I basically did the same through Cloudflare.

**Comment by jariz** [comment]
Thanks!
