### ISSUE TITLE
Alpine images

### ISSUE THREAD

**Issue by karlprieb** [angristan/feedbin-docker#35]
Why not use Alpine as base for the images?
They're smaller, more secure and sometimes faster.
If there's nothing against Alpine can I create a PR changing the Dockerfiles?

Thanks for this project... without this project is almost impossible to self host Feedbin!

**Comment by angristan** [comment]
Alpine is not always the best choice: https://pythonspeed.com/articles/alpine-docker-python/. I don't really care about image size anymore to be honest. I don't mind using Alpine if you want to make a PR though 🙂

**Comment by karlprieb** [comment]
Yep... I suggested Alpine because it has less things so less surface area for security issues, but I agree that sometimes it's a pain to deal with musl. I run alpine on my laptop and server so I'm little biased, but as we can see on this article for Python the situation is horrible. I know that for node is great, but really don't know for ruby as I never worked with ruby.
So let's just let the things how they are now (it's working fine) and if someone need smaller images I can create a PR for that as I'm already using here.

Thanks for your reply!

**Comment by karlprieb** [comment]
I'll close this as I discovered that rubyjs doesn't work without glibc (used for v8).
