### ISSUE TITLE
Images aren't downloading in feed view when using Minio

### ISSUE THREAD

**Issue by flosoft** [angristan/feedbin-docker#43]
The feedbin-image service can not connect to the S3 bucket when using Minio.

Additional configuration is required in the file `lib/s3_pool.rb` on the image host.
```ruby
S3_POOL = ConnectionPool.new(size: 10, timeout: 5) do
  Fog::Storage.new(
    provider: "AWS",
    aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
    aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
    persistent: true,
    host: 'minio.your.tld',
    endpoint: 'https://minio.your.tld',
    path_style: true,
  )
end
```

More info: https://github.com/minio/docs/blob/legacy/docs/fog-aws-for-ruby-with-minio.md

**Comment by karlprieb** [comment]
There's already a PR from @angristan from a year ago https://github.com/feedbin/image/pull/5

**Comment by karlprieb** [comment]
I just recreated @angristan PR to fix that https://github.com/feedbin/image/pull/10

**Comment by angristan** [comment]
Should be fixed then!
