### ISSUE TITLE
Android app and self-hosted instance?

### ISSUE THREAD

**Issue by agrider** [angristan/feedbin-docker#52]
Has anyone gotten a self-hosted version working with any android client RSS readers? I have my instance properly exposed via reverse proxy and have host rewriting being done to the api endpoint such that I'm able to use it successfully from Postman on api.feedbin.mydomain.tld, but I'm having trouble getting any clients to connect. Palabre is what I'm trying to use right now as it's the only one I've found so far that allows self-hosted instances, but all it does is spin when attempting to connect.

**Comment by qcasey** [comment]
I've been successfully using the app FeedMe with this self hosted. You log into your instance directly, rather than using the traditional meta RSS feed

**Comment by agrider** [comment]
Thanks @qcasey , worked instantly. Guess the couple apps I tried both had problems.

**Comment by majur** [comment]
Any iOS alternative?
