### ISSUE TITLE
"Extract full content" feature does not work

### ISSUE THREAD

**Issue by ldexterldesign** [angristan/feedbin-docker#6]
Hi,

Hope you're safe

Disclaimer: I don't know what this means in the readme so I invite you to enhance it, specifically the "update the domains" part:

> Copy caddy/example.Caddyfile to caddy/Caddyfile and update the domains

I left the caddy file default but had problems with letsencrypt

This could be due to [r]ate limiting because I must have been hammering something during my copious setup attempts. If you'd be kind enough to clarify the "update the domains" part of the readme then happy to retry in a week or so (I read rate limiting can last days/weeks 😕)..?

Here's what worked for me:

```
127.0.0.1:3000 {
  gzip
  proxy / http://feedbin-web:3000 {
    transparent
  }
}

127.0.0.1:8081 {
  gzip
  proxy / http://camo:8081 {
    transparent
  }
}

127.0.0.1:9000 {
  gzip
  proxy / http://minio:9000 {
    transparent
  }
}
```

```
# Rails
[...]
FEEDBIN_HOST=127.0.0.1
FORCE_SSL=false
```

Correct me if I'm wrong but `localhost`, instead of `127.0.0.1`, won't work because [t]his

Aside, the "(extract/sticky) full content" feature doesn't seem to load full content (ever) for me - I presume this is because I'm not using SSL/HTTPS?:

* If yes then how can I fix this
* If no then any idea what the reason is

<img width="760" alt="Screenshot 2020-03-28 at 05 50 30" src="https://user-images.githubusercontent.com/1715809/77815131-3002ba80-70b8-11ea-929e-843530b3bbc7.png">

<img width="232" alt="Screenshot 2020-03-28 at 05 46 29" src="https://user-images.githubusercontent.com/1715809/77815097-83c0d400-70b7-11ea-9c7e-82b29b8eeafa.png">

If you have any issues (e.g. questions/queries) then happy to help

Hope to hear back

Sincerely

r: https://letsencrypt.org/docs/rate-limits
t: https://letsencrypt.org/docs/certificates-for-localhost

**Comment by angristan** [comment]
You can see if you have been rate limited in Caddy's logs :)

I think "extract full content" is an option for Feedbin's scrapper. Like if a website only provides an excerpt in their feed, Feedbin would try to get the whole content. If that's not working, I can't see how it's related to HTTPS, probably a Feedbin bug.

**Comment by ldexterldesign** [comment]
> You can see if you have been rate limited in Caddy's logs :)

I was monitoring the docker logs (assume they're the same as caddy logs but will explore further next time I attempt an install with default configs)

> I think "extract full content" is an option for Feedbin's scrapper. Like if a website only provides an excerpt in their feed, Feedbin would try to get the whole content. If that's not working, I can't see how it's related to HTTPS, probably a Feedbin bug.

I just came from the feedbin free trial where it worked fine so I don't think it's a bug

I've experienced this issue before with [f]eeder:

```
Mixed Content: The page at 'https://feeder.co/reader' was loaded over HTTPS, but requested an insecure resource 'http://www.bbc.co.uk/earth/story/20150727-mystical-hair-ice-riddle-solved'. This request has been blocked; the content must be served over HTTPS.
```

I used to get this console error if HTTPS setting wasn't on

I notice you touch on mixed content in the readme..?

f: https://feeder.co

**Comment by angristan** [comment]
Oops, I'm indeed getting a 500 when clicking on extract full content:

```
feedbin-web_1            | I, [2020-03-29T16:40:46.824871 #1]  INFO -- : method=GET path=/extracts/7914/entry format=js controller=ExtractsController action=entry status=500 error='NoMethodError: undefined method `check_for_image' for #<ExtractsController:0x00007f1e283a7e18>' duration=207.92 view=0.00 db=19.65
feedbin-web_1            | F, [2020-03-29T16:40:46.854732 #1] FATAL -- :
feedbin-web_1            | NoMethodError (undefined method `check_for_image' for #<ExtractsController:0x00007f1e283a7e18>):
feedbin-web_1            |
feedbin-web_1            | app/controllers/extracts_controller.rb:18:in `rescue in entry'
feedbin-web_1            | app/controllers/extracts_controller.rb:9:in `entry'
feedbin-web_1            | lib/tld_length.rb:13:in `call'
feedbin-web_1            | lib/basic_authentication.rb:10:in `call'
```

I'm not sure why you think this is a mixed content issue ^^

**Comment by ldexterldesign** [comment]
<img width="1792" alt="Screenshot 2020-03-30 at 06 28 58" src="https://user-images.githubusercontent.com/1715809/77875279-df25ca00-724f-11ea-8c59-352a70a57eed.png">

OK, so I think the HTTP 500 error is because my referrer `Request URL` is `127.0.0.1`:

Request URL: http://127.0.0.1:3000/extracts/104/entry?utf8=%E2%9C%93&extract=true

... so according to this my request is an unsecured HTTP and won't send:

> A Referer header is not sent by browsers if:
> 
> The referring resource is a local "file" or "data" URI.
> An unsecured HTTP request is used and the referring page was received with a secure protocol (HTTPS).
> - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

If correct then the fix would be to ensure I'm using HTTPS host domains (e.g. https://feedbin.domain.tld ?) not local host domains (i.e. 127.0.0.1)

You have some *feedbin.domain.tld stuff setup in `.env` - is this a placeholder variable or something letsencrypt can/will work with?

Sincerely

**Comment by ldexterldesign** [comment]
Presuming this is related...

If I use `.env`:

```
[...]
FORCE_SSL=
FORCE_SSL=true
[...]
```

... then `feedbin_feedbin-web` logs the following (error):

```sh
=> Booting Puma
=> Rails 6.0.2.2 application starting in production 
=> Run `rails server --help` for more startup options
2020-03-30 04:44:02 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
---
2020-03-30 04:44:03 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
```

If I use  `.env`:

```
[...]
FORCE_SSL=false
[...]
```

... then logs yield no errors:

```sh
=> Booting Puma
=> Rails 6.0.2.2 application starting in production
=> Run `rails server --help` for more startup options
```

FYI:

```
[...]
# Rails
RACK_ENV=production
RAILS_ENV=production
PORT=3000
SECRET_KEY_BASE=password
DEFAULT_URL_OPTIONS_HOST=feedbin.domain.tld
PUSH_URL=https://feedbin.domain.tld
FEEDBIN_URL=https://feedbin.domain.tld
FEEDBIN_HOST=127.0.0.1
FORCE_SSL=false
[...]
```

Regards

**Comment by ldexterldesign** [comment]
Regarding your log, correct me if I'm wrong but I think you'd be better off looking at browser logs than docker logs because `xhr.send` is a [j]Query (AJAX) function:
 
<img width="1792" alt="Screenshot 2020-03-30 at 07 08 44" src="https://user-images.githubusercontent.com/1715809/77877404-f8ca1000-7255-11ea-883b-5aaf946226c6.png">

```
// Do send the request
// This may raise an exception which is actually
// handled in jQuery.ajax (so no try/catch here)
xhr.send( ( options.hasContent && options.data ) || null );
```

Regards

j: https://devdocs.io/jquery/jquery.ajax

**Comment by ldexterldesign** [comment]
FYI https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns

**Comment by ldexterldesign** [comment]
FYI https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by angristan** [comment]
Sorry but... no 😄

`500` is a backend issue, you're looking in the wrong places. This is not related to HTTPS, CORS, XHR, Referrer... The front-end is doing good. If we get a error 500, the problem is on the server side.

As pointed out above, **this** is the issue:

```
feedbin-web_1            | I, [2020-03-29T16:40:46.824871 #1]  INFO -- : method=GET path=/extracts/7914/entry format=js controller=ExtractsController action=entry status=500 error='NoMethodError: undefined method `check_for_image' for #<ExtractsController:0x00007f1e283a7e18>' duration=207.92 view=0.00 db=19.65
feedbin-web_1            | F, [2020-03-29T16:40:46.854732 #1] FATAL -- :
feedbin-web_1            | NoMethodError (undefined method `check_for_image' for #<ExtractsController:0x00007f1e283a7e18>):
feedbin-web_1            |
feedbin-web_1            | app/controllers/extracts_controller.rb:18:in `rescue in entry'
feedbin-web_1            | app/controllers/extracts_controller.rb:9:in `entry'
feedbin-web_1            | lib/tld_length.rb:13:in `call'
feedbin-web_1            | lib/basic_authentication.rb:10:in `call'
```

As you can see on the first line `method=GET path=/extracts/7914/entry`, this is what the XHR request is calling.

**Comment by ldexterldesign** [comment]
Mmm, currently looking into caddy/camo as being the culprit...

**Comment by angristan** [comment]
I doubt they would be the culprit... I opened an issue upstream, hopefully we'll get some insights!
