### ISSUE TITLE
OAuth Integrations like Pocket or Evernote?

### ISSUE THREAD

**Issue by agrider** [angristan/feedbin-docker#62]
Trying to determine if the Pocket integration is broken in my setup or if it just doesn't work for self-hosted. Does anyone have Pocket (or Evernote, or any other integration that works via the below callstack for OAuth) working on a self-hosted instance and if so how did you resolve the below error to get it working? The following POST happens when I click `activate` on the pocket integration under the share & save menu and results in a 500 error page. No OAuth popup or redirect takes place, just a transition straight to the 500 error page. 

```
today at 9:33 AM  I, [2021-04-08T14:33:26.165002 #1]  INFO -- : method=POST path=/supported_sharing_services format=html controller=SupportedSharingServicesController action=create status=500 error='NoMethodError: undefined method `token' for nil:NilClass' duration=166.00 view=0.00 db=0.84
today at 9:33 AM  F, [2021-04-08T14:33:26.172799 #1] FATAL -- :   
today at 9:33 AM  NoMethodError (undefined method `token' for nil:NilClass):
today at 9:33 AM    
today at 9:33 AM  app/controllers/supported_sharing_services_controller.rb:122:in `oauth_request'
today at 9:33 AM  app/controllers/supported_sharing_services_controller.rb:87:in `authorize_service'
today at 9:33 AM  app/controllers/supported_sharing_services_controller.rb:5:in `create'
today at 9:33 AM  lib/tld_length.rb:13:in `call'
today at 9:33 AM  lib/basic_authentication.rb:10:in `call'
`

**Comment by agrider** [comment]
Just thought I'd check in again and see, does anyone have sharing to Pocket working on their instance or do all self hosters get a 500 when attempting to activate the integration?

**Comment by agrider** [comment]
Nevermind, I just figured it out. Thanks to @karlprieb 's PR #65 where I saw how he enabled Twitter integration, I realized that a similar ENV var is needed for Pocket (POCKET_CONSUMER_KEY). The app itself doesn't throw a very useful exception if there is no key set, it just chokes and dies, which made it hard to track down. Could be that I was just being daft, but might be good to just add some general doc to the .env example in this project (taken from env.example in the upstream) with these keys for the various integrations.

```
export EVERNOTE_KEY=
export EVERNOTE_SECRET=

export INSTAPAPER_KEY=
export INSTAPAPER_SECRET=

export POCKET_CONSUMER_KEY=

export READABILITY_API_TOKEN=
export READABILITY_READER_KEY=
export READABILITY_READER_SECRET=

export TUMBLR_KEY=
export TUMBLR_SECRET=
````

**Comment by karlprieb** [comment]
Can you open a PR adding and documenting those variables?

**Comment by agrider** [comment]
It was already on my personal backlog before you asked. Unfortunately, with a baby on the way in a couple of months, I have to be honest that I have no idea when I will get to it, which is why I opted to document in the issue and close it rather than take the time to open a PR. I'll hopefully get around to it soonish though.
