### ISSUE TITLE
Feedbin API

### ISSUE THREAD

**Issue by cf-vnkr** [angristan/feedbin-docker#64]
Thank you for this project, it's amazing.

Could you please advise if this configuration supports Feddbin API? It doesn't seem to expose the separate API endpoint. Is there a different URL (from the default api.feedbin.com) that is exposing the API?

**Comment by cf-vnkr** [comment]
Looking at Feebin's code I believe it's looking at `api.` host name for API requests but simply adding this host name to the config of this project doesn't help - the server returns "Blocked host" error.

**Comment by karlprieb** [comment]
Hey I had to add the follow header on my reverse proxy to trick the server so I can access the api:
```
reverse_proxy feedbin-web:3000 {
    header_up Host api.feedbin.com
}
```

Also on the `.env` file add `FEEDBIN_HOST=your-host.com,api.feedbin.com` :)

**Comment by karlprieb** [comment]
@cf-vnkr can we close this issue as this is already built-in on this project?
https://github.com/angristan/feedbin-docker/blob/915b7bac52ebc401256ee13043fb1d993095e24a/caddy/example.Caddyfile#L39

**Comment by cf-vnkr** [comment]
A qustion if I may: in this case what do you set for `FEEDBIN_API_HOST`?

**Comment by karlprieb** [comment]
Anything that you want... it can't be the same domain as the main domain.
I use api.<domain.tld> for example.
